version: '3'
services:
  nginx:
    image: nginx 
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - ".:/var/www/html"
  php:
    build:
      context: wallabagContainer/
      args:
        USER_ID: ${USER_ID:-www-data}
        GROUP_ID: ${GROUP_ID:-www-data}
    volumes:
      - ".:/var/www/html"
